// <auto-generated />
using EquipmentLoanApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EquipmentLoanApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250411005932_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EquipmentLoanApi.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<long>("Cpf")
                        .HasColumnType("bigint");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<bool>("Status")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("Cpf");

                    b.HasIndex("ProductId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("EquipmentLoanApi.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Microfone",
                            Quantity = 12
                        },
                        new
                        {
                            Id = 2,
                            Name = "Datashow",
                            Quantity = 4
                        },
                        new
                        {
                            Id = 3,
                            Name = "Televisor",
                            Quantity = 2
                        },
                        new
                        {
                            Id = 4,
                            Name = "Aparelho de DVD",
                            Quantity = 7
                        },
                        new
                        {
                            Id = 5,
                            Name = "Caixa de Som",
                            Quantity = 15
                        },
                        new
                        {
                            Id = 6,
                            Name = "Projetor",
                            Quantity = 3
                        },
                        new
                        {
                            Id = 7,
                            Name = "Sistema de Áudio",
                            Quantity = 2
                        },
                        new
                        {
                            Id = 8,
                            Name = "Equipamento de Streaming",
                            Quantity = 6
                        },
                        new
                        {
                            Id = 9,
                            Name = "Gravador Digital",
                            Quantity = 8
                        });
                });

            modelBuilder.Entity("EquipmentLoanApi.Models.User", b =>
                {
                    b.Property<long>("Cpf")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Cpf"));

                    b.Property<bool>("IsConsumer")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Cpf");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("EquipmentLoanApi.Models.Order", b =>
                {
                    b.HasOne("EquipmentLoanApi.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("Cpf")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EquipmentLoanApi.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
